### ISSUE TITLE
Firefox bar

### ISSUE THREAD

**Issue by paulovr** [vooze/arc-darker-ubuntu#11]
Two different colors in firefox. a bug?
thank you!!!

![captura de pantalla de 2016-05-02 20-10-55](https://cloud.githubusercontent.com/assets/19158433/14970787/375ff83a-10a2-11e6-96b9-2cf28d6eef7f.png)

**Comment by vooze** [comment]
Probably something to do with the new GTK3 firefox. I will look into it :)

**Comment by vooze** [comment]
Fixet :) Please update the theme to see the changes.

Apparently the new firefox GTK3 takes some of the colors from the menu section in the GTK theme, but does not support some functions. But I managed to fix it, without breaking anything ;) I hope.

**Comment by paulovr** [comment]
Now is great, the theme and amazing ..
thanks..
