### ISSUE TITLE
shadow in window

### ISSUE THREAD

**Issue by paulovr** [vooze/arc-darker-ubuntu#12]
I have a question. How can I do to increase the shadows of the windows, as well as the theme Ambiance? I like the deeper shadows.

**Comment by vooze** [comment]
Can you give me an example? But i'm not really sure to be honest.

**Comment by paulovr** [comment]
Yes! I can. 

Shadow standard edge

![captura de pantalla de 2016-06-24 13-37-20](https://cloud.githubusercontent.com/assets/19158433/16344190/c26ef2c6-3a11-11e6-925f-7ae44fdbd067.png)

If it is possible to leave the window borders with this shadow size?

![captura de pantalla de 2016-06-24 13-40-45](https://cloud.githubusercontent.com/assets/19158433/16344171/a6411728-3a11-11e6-9535-368dca52c593.png)

thank you!!

**Comment by vooze** [comment]
I personally like them as they are, but if you want, you can have a look at this https://github.com/horst3180/Arc-theme/issues/8 and play with it yourself :)

Closing for now, will maybe look at it another time.
