### ISSUE TITLE
Any love for Fedora?

### ISSUE THREAD

**Issue by hadig** [vooze/arc-darker-ubuntu#13]
Can you maybe consider a Fedora version of this? I think Fedora is a good stable base for a fully gnome version of this arc theme with your nice touches. Thank you!

**Comment by vooze** [comment]
Not at the moment i'm afraid. This is specifically customized for Ubuntu 16.04 LTS, which I think I will be using for 2 years. I have thought about moving to fedora from time to time, but will probably wait until 16.04.1 to see if this becomes stable.

I would suggest you use Arc theme and then customize it yourself. It's not really very difficult. Just look the the CSS code and change the colors to match your liking :)
