### ISSUE TITLE
Updates for GTK+ 3.20

### ISSUE THREAD

**Issue by d3v2null** [vooze/arc-darker-ubuntu#17]
Any plans to have this beautiful theme working with GTK3.20 please?

**Comment by vooze** [comment]
Not at the moment, since I use ubuntu 16.04 I myself. I don't have the time to update each 6 months. :( sorry.

I would recommend you to download arc and change the colors yourself, it it's just that difficult :)

**Comment by criptodev** [comment]
@vooze This theme is like flatabulous? https://github.com/anmoljagetia/Flatabulous

Do you need help with this project?

**Comment by criptodev** [comment]
Im a junior web designer if you need help, contact me. I like your project.
