### ISSUE TITLE
Theme goes bananas on minimizing an app with client-side decorations

### ISSUE THREAD

**Issue by merlijn-sebrechts** [vooze/arc-darker-ubuntu#4]
1. Install this theme and switch to it
2. install Gnome Clocks
3. Open Gnome clocks and minimize it a few times.

Result: Freezes, unity bar disappears, ..

Numix is having the same issues BTW

**Comment by vooze** [comment]
Yes. I know. Seems everything but themes made out of Ambiance have this issue... I'm thinking Ubuntu devs need to fix it.

**Comment by vooze** [comment]
Added a bug and help wanted. If someone have some idea how to fix this, please tell me. It works in ambiance so it should be fixable, I just don't know how.

**Comment by manglaneso** [comment]
Have you filled a bug report?

**Comment by vooze** [comment]
@manglasape not yet. But you can see what the original arc owner says here: https://github.com/horst3180/arc-theme/issues/454

**Comment by manglaneso** [comment]
Seems like someone already reported it! https://bugs.launchpad.net/ubuntu/+source/compiz/+bug/1570843

**Comment by vooze** [comment]
@manglasape good find! I have commented on the issue and marked myself as affected.

**Comment by vooze** [comment]
Just testet with cinnamon 3.0, and that works just fine. So it's a bug in unity/compiz.

**Comment by vooze** [comment]
Now fixed in unity from proposed. Closing.

**Comment by merlijn-sebrechts** [comment]
Awesome! Thanks!

2016-05-27 22:10 GMT+02:00 Joakim Koed notifications@github.com:
