### ISSUE TITLE
Wallpaper on the first screenshot?

### ISSUE THREAD

**Issue by marvinroger** [vooze/arc-darker-ubuntu#5]
Hi,

I really like the wallpaper in this screenshot:

![Screenshot](https://camo.githubusercontent.com/af80cba4e44e7dcd9a453c98fa401ff420292c4b/687474703a2f2f692e696d6775722e636f6d2f424a624c5247462e706e67)

Can you please tell us where you found it?

Thanks!

**Comment by vooze** [comment]
Sure, here you go https://alpha.wallhaven.cc/wallpaper/310

**Comment by marvinroger** [comment]
Thanks a lot. :smiley:
