### ISSUE TITLE
Nautilus

### ISSUE THREAD

**Issue by leoheck** [vooze/arc-darker-ubuntu#6]
Great bro this is what I was looking for since I switched to arc.

I would like to ask you to increase the contrast a bit in the disabled-menu items if it is possible. Take a look:
![selection_030](https://cloud.githubusercontent.com/assets/1277920/14771512/1cfb893a-0a64-11e6-9ab2-0d220de79a74.jpg)

Another question is: Do you know why my nautilus is like this [arc-theme issue](https://github.com/horst3180/arc-theme/issues/298#issuecomment-213862747)

Regarding the same issue, do you know how to improve the nautilus sidebar as I reported in this [thread](https://github.com/horst3180/arc-theme/issues/298#issue-114546784)? 

By the way, I am using ubuntu 16.04 upgraded from 15.10, then from 16.04, then from 12.04 :) (maybe I need a fresh install)

**Comment by vooze** [comment]
Thank you for reporting this.  I will definitely look into the first thing ASAP. Regarding the other issues I don't know. That's somthing for the original theme to fix, I'm not really a CSS coder just trying my best :-)

If it does get fixet by arc please tell me so I can look into it. 

Will return later with, hopefully, a fix for first issue.

**Comment by vooze** [comment]
Ask and you shall receive. First issue is now fixed.
Hope you like the new color. It's based on white now, with 0.45 so it's like grayish, instead of blueish.

**Comment by vooze** [comment]
@leoheck can you check if it looks okay now?

**Comment by leoheck** [comment]
I have updated yesterday and the disabled-text looks far better now, thank you very much.
