### ISSUE TITLE
Terminal color scheme wrong/ugly

### ISSUE THREAD

**Issue by cwildfoerster** [vooze/arc-darker-ubuntu#9]
I just installed your theme on two of my Ubuntu 16.04 machines and the theme looks really good, except for the terminal, everything is white and looks strange, not like on your screenshots. I don't  know why, everything is still the default, but have a look:
![Imgur](http://i.imgur.com/RstLEpU.png)

**Comment by vooze** [comment]
Hi @cwildfoerster 

You can go into preferences -> profiles > edit profile and edits the colors.

If you want the dark to match, you can use this background (#282828) (for blue thats #2f343f)
White is just #FFFFFF

See more here: https://help.gnome.org/users/gnome-terminal/stable/app-colors.html.en

I will probably change the theme to do that by default, but for now, you can do it yourself :)

**I'll leave this open until it's properly fixed.**

**Comment by vooze** [comment]
I'll leave this open, until its fixet by default.

**Comment by cwildfoerster** [comment]
@vooze Thank you very much for your fast reply... it looks good now. I just thought if i leave "use system theme" checked that everything should be fine. I and i think many others would be really pleased if this could be done via your repository or script automatically.

**Comment by vooze** [comment]
I agree. I will try to do it when I have some time :-)

**Comment by vooze** [comment]
Fixed.
